episode-355/store-before/config/routes.rb
Store::Application.routes.draw do
  resources :products
  root to: 'products#index'
end

episode-355/store-before/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :products
end

episode-355/store-before/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  attr_accessible :name, :price, :category_id, :released_at, :discontinued_at, :stock

  def self.search(query)
    where("released_at <= ? and (discontinued_at is null or discontinued_at > ?) and stock >= ? and name like ?", Time.zone.now, Time.zone.now, 2, "%#{query}%")
  end
end

episode-355/store-before/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

episode-355/store-before/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.search(params[:search])
  end

  def show
    @product = Product.find(params[:id])
  end
end

episode-355/store-before/app/helpers/application_helper.rb
module ApplicationHelper
end

episode-355/store-before/app/helpers/products_helper.rb
module ProductsHelper
end

episode-355/store-before/app/views/products/index.html.erb
<h1>Products</h1>

<%= form_tag products_path, method: :get do %>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", name: nil %>
<% end %>

<table id="products">
  <tr>
    <th>Product Name</th>
    <th>Release Date</th>
    <th>Price</th>
  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= link_to(product.name, product) %></td>
    <td><%= product.released_at.strftime("%B %e, %Y") %></td>
    <td><%= number_to_currency(product.price) %></td>
  </tr>
<% end %>
</table>

episode-355/store-before/app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<p>
  <b>Price:</b>
  <%= number_to_currency @product.price %>
</p>

<p>
  <b>Release Date:</b>
  <%= @product.released_at.strftime("%B %e, %Y") %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category.name %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Destroy', @product, method: :delete, confirm: "Are you sure?" %> |
<%= link_to 'List Products', products_path %>